cursor:
  x: 24.137
  y: 21.056
  z: 4.052
move:
  step: 0.1
scan:
  range: 2.0
  x:
    end: 28.386
    start: 13.082
    step: 0.153
  y:
    end: 65.0
    start: 0.0
    step: 0.65
  z:
    end: 25.017
    start: 9.712
    step: 0.306
scanner: piezo
