cursor:
  x: 24.137
  y: 21.056
  z: 4.052
move:
  step: 0.1
scan:
  range: 2.0
  x:
    end: 65.0
    start: 0.0
    step: 0.65
  y:
    end: 65.0
    start: 0.0
    step: 0.65
  z:
    end: 30.0
    start: 0.0
    step: 0.6
scanner: piezo
