move:
  z_step: 0.1
  piezo_xy_step: 0.1
  galvo_xy_step: 0.003
z_scan_range: 10
piezo_scan:
  range: 2.0
  cursor:
    x: 36.958
    y: 26.361
    z: 23.005
  x:
    end: 65.0
    start: 0.0
    step: 0.65
  y:
    end: 65.0
    start: 0.0
    step: 0.65
  z:
    end: 30.0
    start: 0.0
    step: 0.6
galvo_scan:
  range: 0.1
  cursor:
    x: 0.0
    y: 0.0
    z: 0.0
  x:
    end: 0.3
    start: -0.3
    step: 0.006
  y:
    end: 0.3
    start: -0.3
    step: 0.006
  z:
    end: 30.0
    start: 0.0
    step: 0.6
scanner: galvo
