cursor:
  x: 42.756
  y: 25.33
  z: 0.0
move:
  step: 0.1
scan:
  range: 2.0
  x:
    end: 43.8
    start: 41.8
    step: 0.02
  y:
    end: 26.3
    start: 24.3
    step: 0.02
  z:
    end: 30.0
    start: 0.0
    step: 0.3
