galvo_scan:
  cursor:
    x: 0.0
    y: 0.0
    z: 0.0
  line_frequency_index: 0
  line_frequency_value: 1.0
  range: 0.1
  x:
    end: 0.4
    start: -0.4
    step: 0.008
  y:
    end: 0.4
    start: -0.4
    step: 0.008
  z:
    end: 30.0
    start: 0.0
    step: 0.6
move:
  galvo_xy_step: 0.001
  piezo_xy_step: 0.1
  z_step: 0.1
piezo_scan:
  cursor:
    x: 25.0
    y: 25.0
    z: 25.0
  range: 2.0
  x:
    end: 65.0
    start: 0.0
    step: 0.65
  y:
    end: 65.0
    start: 0.0
    step: 0.65
  z:
    end: 30.0
    start: 0.0
    step: 0.6
scanner: galvo
z_scan_range: 10.0
